- title: ACIAH
  values:
  - label: E-mail association ACIAH
    text: aciah@free.fr
    alt: L'e-mail officiel de l'association ACIAH
  - label: Numéro association ACIAH
    text: 09 77 81 55 98
    alt: le numéro de téléphone officiel de l'association ACIAH
  - label: But asso ACIAH
    text: Proposer un OS adapté aux personnes handicapées, avec un lecteur d'écran
      intégré, des raccourcis et... CopColl !
    alt: Pas besoin
- title: Machin
  values:
  - label: Machin
    text: Bidule
    alt: Muche
