Adresses:
  Papa: 69 Rue QQchose, 12345 Une-ville
  Papi: 33 Avenue Autre-Machin, 67890 Une-autre-ville
  qsqs: qss
  ds: s
  dd: ds
Codes postaux de villes:
  Nantes: 44000
  Riaillé: 44440
  sqssq: qqssqazs
Écoles:
  Maternelle/Primaire:
    TPS: Camille Claudel
    Reste: Robert Doisneau
  Collège: Louis Pasteur
  Lycée: Livet
  sd: sd
Recettes:
  Ingrédients Flammenkuche:
  - Pâte à pizza
  - Fromage blanc
  - Oignons
  - Lardons
